@extends('masters.default_single')

@section('content')

<div class="row">
	<h1>Terms & Conditions</h1>
	<p>I (the "Customer") agree with the following terms and conditions for the provision of mining services (the "Agreement") as described hereunder between the following parties:
	1.	Crypto Wave Capital B.V., Heinsbergerweg 56, Roermond, The Netherlands, ("Service Provider"); and
	2.	me, the Customer.
	</p>

	<p>
	Pursuant to the terms of this Agreement, the Service Provider will make available to the Customer computing power in the mining capacity of the Service Provider.
	</p>

	<p>
	<h4>1. Services</h4>
	The Service Provider agrees to provide to the Customer with the partial output of its mining capacity (the "Services") subject to the following terms:</br><br/>
	<strong>Maturity:</strong> 1 Year (starting on 1 august 2014)<br/>
	<strong>Mining Power:</strong> 1 MH/s<br/>
	<strong>Payout frequency:</strong> Quarterly<br/>
	<strong>Payment output:</strong> BitCoin or Fiat currency<br/><br/>
	The Service Provider will be responsible for the maintenance of the relevant technical equipment (software/hardware) that is required to execute the above service. The Customer will receive Payment in accordance with the above Mining Power and of applicable Fees as per 2.b. The Customer also acknowledges that the above Services will be rendered on a best effort basis. The Service Provider ensures that it maintains all facilities and the relevant supplies in good working order. The Payment output averages the revenue generated by the 6 largest scrypt mining pools minus a 10% management fee that covers all costs invoked by the Service Provider (as a reference, yet not defining, the website PoolPicker.eu can be used to estimate the revenue). The actual Payment output can deviate from this average.
	</p>

	<p>
	<h4>2. Remuneration</h4>
	As a consideration for the Services the Customer agrees to pay to the Service Provider an amount of (the "Fee") upfront. The Fee depends on the total amount of certificates bought. When buying 1, 5, 10 or 25 certificates the Fee per certificate is €75, €70, €65 and €60 respectively.
	</p>

	<p>
	<h4>3. Limitation of Liability</h4>
	The Service Provider shall not be liable for any damages incurred by the Customer as a result of force majeur which shall include any disruption or breakdown of a Coin market.
	</p>

	<p>
	<h4>4. Data Protection</h4>
	The Customer agrees to the processing of its personal data provided in the context of this Agreement for the purpose described herein and also agrees, until revocation at any time to the storage of its data beyond the above Term. Should the Service Provider be required to obtain any further data in the context of providing its services, the Customer will without undue delay provide the relevant data so required by the Service Provider
	</p>

	<p>
	<h4>5. Governing Law, Language and Miscellaneous</h4>
	This Agreement is governed by Dutch law. To the extent permitted by applicable law the parties agree that the competent courts of Amsterdam shall have non-exclusive jurisdiction to hear and determine any suit, action or proceeding, and to settle any disputes, which may arise out of or in connection with this Agreement
	</p>

</div>

@stop
